format_version: 10
pipelines:
  gradle-demo-build:
    group: cdp
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      git:
        git: https://github.com/ujjwalvns/gradle-demo.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - gradle-demo-build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_project:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: dockerhub
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/gradle-service
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - gradle build
                command: /bin/sh
                run_if: passed
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/gradle-service:$GO_PIPELINE_LABEL . -f Dockerfile
                command: /bin/bash
                run_if: passed
