format_version: 10
pipelines:
  gradle-build-test:
    group: cdp
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/ujjwalvns/gradle-demo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - gradle-build-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_project:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: dockerhub
                store_id: dockerhub
                configuration:
                  options:
                    BuildFile: ''
                    Tag: ${GO_FROM_REVISION_GIT}
                    Image: ${DOCKERHUB_USERNAME}/gradle-service
            tasks:
            - exec:
                arguments:
                - -c
                - gradle build
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/gradle-service:${GO_FROM_REVISION_GIT}
                  . -f Dockerfile
                command: /bin/bash
                run_if: passed
