format_version: 3
pipelines:
  gradle-demo-build:
    group: IDFC
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/Ankitchandre/gradle-demo.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - gradle-demo-build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: dockerhub
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/gradle-demo
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/gradle-demo:$GO_PIPELINE_LABEL . -f Dockerfile
                command: /bin/bash
                run_if: passed
